name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
        matrix:
            os: [ubuntu-18.04, ubuntu-20.04]#macos-latest
            build_type: [Release, Debug]
    steps:
    - uses: actions/checkout@v2

    - name: "setup ubuntu"
      shell: bash 
      run: |
        sudo apt-get update
        sudo apt-get install git
        git clone https://github.com/Lhumd/ubuntu_installation_scripts.git
